DROP TABLE IF EXISTS public.orders;

CREATE TABLE public.orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    order_ts TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (
        status IN ('pending', 'paid', 'packed', 'shipped', 'cancelled')
    ),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(10, 2) NOT NULL CHECK (unit_price >= 0),
    region VARCHAR(20) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

INSERT INTO public.orders (
    order_id, customer_id, order_ts, status, quantity,
    unit_price, region, updated_at
)
SELECT
    sequence_number,
    1 + (sequence_number % 100000),
    TIMESTAMPTZ '2024-01-01 00:00:00+00'
        + (sequence_number % 900) * INTERVAL '1 day'
        + (sequence_number % 86400) * INTERVAL '1 second',
    (ARRAY['pending', 'paid', 'packed', 'shipped', 'cancelled'])
        [1 + (sequence_number % 5)],
    1 + (sequence_number % 10),
    ROUND((5 + ((sequence_number::BIGINT * 7919) % 20000) / 100.0)::NUMERIC, 2),
    (ARRAY['North', 'South', 'East', 'West'])
        [1 + (sequence_number % 4)],
    TIMESTAMPTZ '2024-01-01 00:00:00+00'
        + (sequence_number % 900) * INTERVAL '1 day'
FROM generate_series(1, 1000000) AS generated(sequence_number);

SELECT setval(
    pg_get_serial_sequence('public.orders', 'order_id'),
    (SELECT MAX(order_id) FROM public.orders),
    true
);

ANALYZE public.orders;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cdc_reader') THEN
        CREATE ROLE cdc_reader
            WITH LOGIN REPLICATION PASSWORD 'cdc-demo-password';
    END IF;
END
$$;

ALTER ROLE cdc_reader PASSWORD 'cdc-demo-password';
GRANT CONNECT ON DATABASE shop TO cdc_reader;
GRANT USAGE ON SCHEMA public TO cdc_reader;
GRANT SELECT ON public.orders TO cdc_reader;
